### PR TITLE
Add Unit Test [Closes #3]

### LINKED ISSUE #3: Add unit tests
To ensure nothing breaks when changing the code, would be great to have unit tests. See the [hubot-example test](https://github.com/hubot-scripts/hubot-example/blob/master/test/hello-world_test.coffee) for details on writing tests.

Moved from https://github.com/mihai/hubot-team/issues/5

### PR DESCRIPTION
**Pull request by EdgarOrtegaRamirez**
This was possible using the following tools:
- Mocha (https://github.com/mochajs/mocha)
- Chai (https://github.com/chaijs/chai)
- Sinon (https://github.com/cjohansen/Sinon.JS)

**Install npm dependencies and run tests!**

``` sh
npm install && npm test
```

Closes #3

### CODE REVIEW

**Comment by charly-palencia** [comment]
@mihai  what about this PR? :)

**Comment by mihai** [comment]
> what about this PR? :)

Sorry for the delay guys, I will (hopefully) get some time towards the end of next week to check this out.

**Comment by charly-palencia** [comment]
No problem :thumbsup:

**Comment by EdgarOrtegaRamirez** [comment]
@mihai ping

**Comment by josegonzalez** [comment]
pong the witch is dead

**Pull request closed without merging**
