### PR TITLE
Adding test and Refactor Code

### PR DESCRIPTION
**Pull request by charly-palencia**
Hi guys!
@mihai 

First of all, i want to say thank for for your great hubot script. you rock!!

I liked so much your idea that i wanted to help you and give my contribution.

Changelog
========

- Added Suite Test (mocha, chai)
- Refactoring code and create new Models:
  * models/team.coffeee: logic model
  * team_manager.coffee: team event handler
  * response_message.coffee: messages  

**IMPORTANT NOTE:** You must upgrade the old data information. with this command before start:

      'hubot upgrade teams'

I want to know if you agree with this changes or if i miss something in all the refactor process

Thanks for your time, i'm looking forward for your response :)

### CODE REVIEW

**Comment by mihai** [comment]
Hi @charly-palencia, @EdgarOrtegaRamirez, thank you for contributing to `hubot-team`!

Will look in detail over the changes this upcoming weekend and leave feedback in this PR, don't forget to add yourselves to [CONTRIBUTORS](https://github.com/hubot-scripts/hubot-team/blob/master/CONTRIBUTORS).

**Comment by mihai** [comment]
Hey guys, sorry for the huge delay, did a skim through the changes and I think it makes it easier and faster if we split this PR in at least 2 different ones:

    1. Refactor team script to use classes
    2. Add unit tests (follow-up to 1.)

As some notes on the commits: please split them in as small units as possible making sure to not update the same block of code from earlier commits in later ones, unless extending that functionality. For example, I would split dfa3cd8 in about 6 commits as the list of changes in its commit message says and b92309c would be squashed in the commit that refactors that bit of code.

In terms of naming, I would not use `players` as the members of a `team`, as the purpose of `hubot-team` is to support a wide range of use cases, not only for sport related team management -- which the name `players` would infer. A simple, clear name would be `members`.

Let me know when the 2 PRs are in place and I can look more into detail in the refactor and extended functionality. Thanks again for the effort! Looking forward to hear back from you.

**Comment by charly-palencia** [comment]
working on your feedbacks! 
:)

**Comment by charly-palencia** [comment]
@mihai I'm closing  this PR to create two new of them with some refactor and improves in which @edgar has been working on . again, thanks for your time.

**Pull request closed without merging**
